"""AddMinimunQuantityForProductModel

Revision ID: 4796ed80a9e6
Revises: a1661e596b9a
Create Date: 2026-04-10 11:51:35.227319

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4796ed80a9e6'
down_revision = 'a1661e596b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_quantity', sa.Integer(), nullable=True))

    op.execute("UPDATE products SET minimum_quantity = 5 WHERE minimum_quantity IS NULL")

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('minimum_quantity', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('minimum_quantity')

    # ### end Alembic commands ###
