"""AddQuantityForProductModel

Revision ID: a1661e596b9a
Revises: f241fe49d6f0
Create Date: 2026-04-10 11:43:02.467177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1661e596b9a'
down_revision = 'f241fe49d6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    op.execute("UPDATE products SET quantity = 0 WHERE quantity IS NULL")

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('quantity', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
