"""AddCategoryForeignKeyToProduct

Revision ID: f241fe49d6f0
Revises: bea57a8e5a1e
Create Date: 2026-04-10 11:23:52.564814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f241fe49d6f0'
down_revision = 'bea57a8e5a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    op.execute("INSERT INTO categories (id, name) VALUES (1, 'Geral') ON CONFLICT DO NOTHING")

    op.execute("UPDATE products SET category_id = 1 WHERE category_id IS NULL")

    # ### end Alembic commands ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category_id', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
